/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_hakkelt_bartwrapper_Bart */

#ifndef _Included_io_github_hakkelt_bartwrapper_Bart
#define _Included_io_github_hakkelt_bartwrapper_Bart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_hakkelt_bartwrapper_Bart
 * Method:    nativeRun
 * Signature: (Lio/github/hakkelt/bartwrapper/Bart/SuccessFlag;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_hakkelt_bartwrapper_Bart_nativeRun
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     io_github_hakkelt_bartwrapper_Bart
 * Method:    nativeRead
 * Signature: (Lio/github/hakkelt/bartwrapper/Bart/SuccessFlag;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_github_hakkelt_bartwrapper_Bart_nativeRead
  (JNIEnv *, jclass, jobject, jobjectArray);

/*
 * Class:     io_github_hakkelt_bartwrapper_Bart
 * Method:    nativeregisterInput
 * Signature: (Lio/github/hakkelt/bartwrapper/Bart/SuccessFlag;Ljava/lang/String;[ILjava/nio/FloatBuffer;)V
 */
JNIEXPORT void JNICALL Java_io_github_hakkelt_bartwrapper_Bart_nativeregisterInput
  (JNIEnv *, jclass, jobject, jstring, jintArray, jobject);

/*
 * Class:     io_github_hakkelt_bartwrapper_Bart
 * Method:    nativeIsMemoryFileRegistered
 * Signature: (Lio/github/hakkelt/bartwrapper/Bart/SuccessFlag;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_hakkelt_bartwrapper_Bart_nativeIsMemoryFileRegistered
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_github_hakkelt_bartwrapper_Bart
 * Method:    nativeRegisterOutput
 * Signature: (Lio/github/hakkelt/bartwrapper/Bart/SuccessFlag;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_hakkelt_bartwrapper_Bart_nativeRegisterOutput
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     io_github_hakkelt_bartwrapper_Bart
 * Method:    nativeLoadMemory
 * Signature: (Lio/github/hakkelt/bartwrapper/Bart/SuccessFlag;Ljava/lang/String;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_io_github_hakkelt_bartwrapper_Bart_nativeLoadMemory
  (JNIEnv *, jclass, jobject, jstring, jintArray);

/*
 * Class:     io_github_hakkelt_bartwrapper_Bart
 * Method:    nativeUnregisterInput
 * Signature: (Lio/github/hakkelt/bartwrapper/Bart/SuccessFlag;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_hakkelt_bartwrapper_Bart_nativeUnregisterInput
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
